### ISSUE TITLE
Add "terminal" as an output format

### ISSUE THREAD

**Issue by pwalsh** [okfn/tellme#10]
When a TellMe is used in another library, it may need to present reports in the terminal, in an informative way.

Thinking to use [asciitable](http://cxc.harvard.edu/contrib/asciitable/) or similar to create such an output.
### Tasks
- [x] add terminal as an output type
- [x] choose lib to create output
- [x] implement basic pattern: e.g., meta data, then table of results.
